//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terminal
    {
        public int TID { get; set; }
        public string Tname { get; set; }
        public System.DateTime TStartTime { get; set; }
        public System.DateTime TEndTime { get; set; }
        public string TDetails { get; set; }
        public int EID { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
